#ifndef TRANSPORT_WIFI_CONFIG_H_
#define TRANSPORT_WIFI_CONFIG_H_

#include "pico/cyw43_arch.h"
#include <stddef.h>

#define TRANSPORT_WIFI_SSID "YOUR_WIFI_SSID"
#define TRANSPORT_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define TRANSPORT_WIFI_HOSTNAME "rb2-runtime"
#define TRANSPORT_WIFI_PORT 4242
#define TRANSPORT_WIFI_COUNTRY CYW43_COUNTRY_GERMANY
#define TRANSPORT_WIFI_USE_DHCP true

#define TRANSPORT_WIFI_STATIC_IP NULL
#define TRANSPORT_WIFI_NETMASK NULL
#define TRANSPORT_WIFI_GATEWAY NULL

#define TRANSPORT_WIFI_RX_QUEUE_SIZE 256

#endif
